services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cash_control
      MYSQL_ROOT_HOST: '%'
    ports:
      - 17433:3306

  php-fpm:
    container_name: php-fpm
    restart: always
    build:
      context: ./php-fpm
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - mysql
      - redis
    volumes:
      - ${PROJECTS_FOLDER}:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
    volumes:
      - ${PROJECTS_FOLDER}:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16